services:
  mysql:
    image: mysql:8.0
    container_name: ${APP_PREFIX}_mysql
    restart: unless-stopped
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  app:
    build:
      dockerfile: docker/php/Dockerfile
      context: .
      args:
        user: aleksandr_aladin
        uid: 1000
    container_name: ${APP_PREFIX}_app
    restart: unless-stopped
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app

  nginx:
    image: nginx:latest
    container_name: ${APP_PREFIX}_nginx
    restart: unless-stopped
    volumes:
      - .:/var/www/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/certs:/etc/nginx/conf.d/certs
    ports:
      - 80:80
      - 443:443

volumes:
  mysql:
    driver: local
